### ISSUE TITLE
Compilation with libsodium fails with pkg-config error, even if it is added in cargo depedencies

### ISSUE THREAD

**Issue by krishnakumar4a4** [dnaq/sodiumoxide#187]
```
error: failed to run custom build command for `libsodium-sys v0.0.16`
process didn't exit successfully: `/Users/user/Work/Leizure/social/target/debug/build/libsodium-sys-931a54f48241e646/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=SODIUM_LIB_DIR
cargo:rerun-if-env-changed=SODIUM_STATIC

--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "`\"pkg-config\" \"--libs\" \"--cflags\" \"libsodium\"` did not exit successfully: exit code: 1\n--- stderr\nPackage libsodium was not found in the pkg-config search path.\nPerhaps you should add the directory containing `libsodium.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'libsodium\' found\n"', src/libcore/result.rs:906:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:69
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:397
   4: std::panicking::begin_panic
             at src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at src/libstd/panicking.rs:538
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:522
   7: std::panicking::try::do_call
             at src/libstd/panicking.rs:498
   8: <core::ops::range::Range<Idx> as core::fmt::Debug>::fmt
             at src/libcore/panicking.rs:71
   9: core::result::unwrap_failed
             at /Users/travis/build/rust-lang/rust/src/libcore/macros.rs:23
  10: <core::result::Result<T, E>>::unwrap
             at /Users/travis/build/rust-lang/rust/src/libcore/result.rs:772
  11: build_script_build::main
             at ./build.rs:20
  12: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:99
  13: <std::rand::reader::ReaderRng<R> as rand::Rng>::fill_bytes
             at src/libstd/panicking.rs:459
             at src/libstd/panic.rs:361
             at src/libstd/rt.rs:59
  14: build_script_build::main

warning: build failed, waiting for other jobs to finish...
error: build failed

Process finished with exit code 101
```

**Comment by krishnakumar4a4** [comment]
I fixed it by installing libsodium library manually in the OS,

In mac, 
            it is ```brew install libsodium```

Verify libsodium with pkg-config:
   ```pkg-config --list-all|grep libsodium``` --> This should return the libsodium entry in pkg-config

**Comment by dnaq** [comment]
I don't understand your issue. These are bindings to libsodium, it needs to be installed for you to use sodiumoxide.

**Comment by krishnakumar4a4** [comment]
@dnaq I added this for beginners. It is not exactly an issue, it is an info.

**Comment by ishaanSejwal** [comment]
Had same issues. I knew I already had `libsodium`. But realised later I did not have `pkg-config`. That did it. So check up on that too just to be sure.
